### ISSUE TITLE
documentation 

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-create#5]
The format of the yaml file needs to be changed in the documentation

The format of the yamls file is as follows: 

```
cloudmesh:
  cluster:
    aws: 
      - name: cluster-1
        nodegroups:
          - name: workers
            instanceType: t2.micro # instance type
            desiredCapacity: 2 # number of nodes
            volumeSize: 20 #min size in GB
            capacityType: 'SPOT' # SPOT or ON_DEMAND
```
